server:
  port: 5003

spring:
  application:
    name: SUBMISSION SERVICE
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/project_submission_service
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
#   jpa:
#     show-sql: true
